apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoapi-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demoapi
  template:
    metadata:
      labels:
        app: demoapi
    spec:
      containers:
      - name: demoapi
        image: msrrepo1.azurecr.io/demowebapi
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: demoapi-svc
spec:
  type: LoadBalancer
  ports:
    - name: "responder"
      port: 80
      targetPort: 80
  selector:
    app: demoapi